# This file is intended for AWS CodeDeploy service
version: 0.0
os: linux
files:
  # copy everything form the ZIP into /FlightFinder
  - source: /
    destination: /FlightFinder
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: aws_codedeploy/install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: aws_codedeploy/build.sh
      timeout: 60
  ApplicationStart:
    - location: aws_codedeploy/start.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: aws_codedeploy/validate.sh
      timeout: 60
  ApplicationStop:
    - location: aws_codedeploy/stop.sh
      timeout: 60
      runas: root
