# This file is intended for AWS CodeDeploy service
version: 0.0
os: linux
files:
  # copy everything form the ZIP into /FlightFinder
  - source: /
    destination: /FlightFinder
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/aws_code_deploy_install.sh
      timeout: 60
      runas: root
  # AfterInstall:
  #   - location: Scripts/RunResourceTests.sh
  #     timeout: 180
  ApplicationStart:
    - location: scripts/aws_code_deploy_start.sh
      timeout: 60
      runas: root
  ApplicationStop:
    - location: scripts/aws_code_deploy_stop.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/aws_code_deploy_validate.sh
      timeout: 3600
      # runas: codedeployuser
